
import "./globals.css";


export const metadata = {
  title: "Ochi Desing ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-zinc-950">{children}</body>
    </html>
  );
}
